name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build Extension
        run: |
          chmod +x gradlew
          ./gradlew :extensions:ar:anime3rb:assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: anime3rb-apk
          path: "**/*.apk"
